language: node_js
node_js:
- stable
before_install:
before_script:
cache:
  directories:
  - node_modules
script:
- yarn build
before_deploy:
- openssl aes-256-cbc -K $encrypted_7952d8bedab8_key -iv $encrypted_7952d8bedab8_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet build ssh root@128.199.212.96:/var/www/westay-react
    on:
      branch: master
after_success:
branches:
  only:
  - master
  - dev
